### ISSUE TITLE
Trying to run Natrix

### ISSUE THREAD

**Issue by meuns** [fbertola/bgfx-python#2] opened 2019-12-09 19:47 UTC
Hi, I'm trying to run Natrix. I use python 3.6 within a virtual env on Ubuntu 18.04. It seems parts of bgfx aren't linked. The python setup didn't report any errors.

```
/home/sylvain/Documents/Natrix/venv/bin/python /home/sylvain/Documents/Natrix/demo/example_window.py
Traceback (most recent call last):
  File "/home/sylvain/Documents/Natrix/demo/example_window.py", line 9, in <module>
    from bgfx import bgfx, as_void_ptr
  File "/home/sylvain/Documents/Natrix/venv/lib/python3.6/site-packages/bgfx_python-0.0.1-py3.6-linux-x86_64.egg/bgfx/__init__.py", line 1, in <module>
    from .utils import *
  File "/home/sylvain/Documents/Natrix/venv/lib/python3.6/site-packages/bgfx_python-0.0.1-py3.6-linux-x86_64.egg/bgfx/utils.py", line 7, in <module>
    from bgfx.bgfx_lib import *
ImportError: /home/sylvain/Documents/Natrix/venv/lib/python3.6/site-packages/bgfx_python-0.0.1-py3.6-linux-x86_64.egg/bgfx/bgfx_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN4bimg12isCompressedENS_13TextureFormat4EnumE

Process finished with exit code 1
```

Do you have any idea ?

Regards

**Comment by fbertola** [comment] 2019-12-15 01:05
Hi! Currently you have to build `bgfx-python` by yourself.
You can simply clone the repository and install it in the same virtual env:
```
$ git clone https://github.com/fbertola/Natrix.git
$ pip install .
```

I'm actually testing an automatic wheel generation pipeline. Let me know if this solves your issue.

**Comment by meuns** [comment] 2019-12-15 10:36
I build bgfx-python and installed it in a shared virtual env with Natrix. I did : `python setup.py install` from bgfx-python, before trying to run Natrix.

**Comment by meuns** [comment] 2019-12-15 10:44
I started from stratch in pycharm :
`
(venv) $ git clone https://github.com/fbertola/Natrix.git
(venv) $ pip install .
(venv) $ pip install glfw
(venv) $ pip install scikit-build
(venv) $ cd ../bgfx-python
(venv) $ python setup.py install
`

But the same error occurs.

**Comment by meuns** [comment] 2019-12-15 10:47
I wish I will find a wheel usable on Windows and Linux for Christmas !

**Comment by fbertola** [comment] 2019-12-16 12:59
I'll look into it, as my main environment is MacOS. Thanks for reporting the issue!

**Comment by fbertola** [comment] 2020-01-07 08:41
@meuns The issue is resolved with the latest commit.

**Closed by fbertola** 2020-01-07 08:41 UTC
